In [1]:
# Import required libraries and dependencies
import pandas as pd
import hvplot.pandas
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
# Load the data into a Pandas DataFrame
df_market_data = pd.read_csv(
    "Resources/crypto_market_data.csv",
    index_col="coin_id")

# Display sample data
df_market_data.head(10)

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                    
bitcoin                              1.08388                     7.60278   
ethereum                             0.22392                    10.38134   
tether                              -0.21173                     0.04935   
ripple                              -0.37819                    -0.60926   
bitcoin-cash                         2.90585                    17.09717   
binancecoin                          2.10423                    12.85511   
chainlink                           -0.23935                    20.69459   
cardano                              0.00322                    13.99302   
litecoin                            -0.06341                     6.60221   
bitcoin-cash-sv                      0.92530                     3.29641   

                 price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                     
bitcoin                              6.57509                      7.67258   
ethereum                             4.80849                      0.13169   
tether                               0.00640                     -0.04237   
ripple                               2.24984                      0.23455   
bitcoin-cash                        14.75334                     15.74903   
binancecoin                          6.80688                      0.05865   
chainlink                            9.30098                    -11.21747   
cardano                              5.55476                     10.10553   
litecoin                             7.28931                      1.21662   
bitcoin-cash-sv                     -1.86656                      2.88926   

                 price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                      
bitcoin                             -3.25185                      83.51840   
ethereum                           -12.88890                     186.77418   
tether                               0.28037                      -0.00542   
ripple                             -17.55245                      39.53888   
bitcoin-cash                       -13.71793                      21.66042   
binancecoin                         36.33486                     155.61937   
chainlink                          -43.69522                     403.22917   
cardano                            -22.84776                     264.51418   
litecoin                           -17.23960                      27.49919   
bitcoin-cash-sv                    -24.87434                       7.42562   

                 price_change_percentage_1y  
coin_id                                      
bitcoin                            37.51761  
ethereum                          101.96023  
tether                              0.01954  
ripple                            -16.60193  
bitcoin-cash                       14.49384  
binancecoin                        69.69195  
chainlink                         325.13186  
cardano                           156.09756  
litecoin                          -12.66408  
bitcoin-cash-sv                    93.73082

In [3]:
# Generate summary statistics
df_market_data.describe()

price_change_percentage_24h  price_change_percentage_7d  \
count                    41.000000                   41.000000   
mean                     -0.269686                    4.497147   
std                       2.694793                    6.375218   
min                     -13.527860                   -6.094560   
25%                      -0.608970                    0.047260   
50%                      -0.063410                    3.296410   
75%                       0.612090                    7.602780   
max                       4.840330                   20.694590   

       price_change_percentage_14d  price_change_percentage_30d  \
count                    41.000000                    41.000000   
mean                      0.185787                     1.545693   
std                       8.376939                    26.344218   
min                     -18.158900                   -34.705480   
25%                      -5.026620                   -10.438470   
50%                       0.109740                    -0.042370   
75%                       5.510740                     4.578130   
max                      24.239190                   140.795700   

       price_change_percentage_60d  price_change_percentage_200d  \
count                    41.000000                     41.000000   
mean                     -0.094119                    236.537432   
std                      47.365803                    435.225304   
min                     -44.822480                     -0.392100   
25%                     -25.907990                     21.660420   
50%                      -7.544550                     83.905200   
75%                       0.657260                    216.177610   
max                     223.064370                   2227.927820   

       price_change_percentage_1y  
count                   41.000000  
mean                   347.667956  
std                   1247.842884  
min                    -17.567530  
25%                      0.406170  
50%                     69.691950  
75%                    168.372510  
max                   7852.089700

In [4]:
# Plot your data to see what's in your DataFrame
df_market_data.hvplot.line(
    width=800,
    height=400,
    rot=90
)

:NdOverlay   [Variable]
   :Curve   [coin_id]   (value)

---

### Prepare the Data

In [5]:
# Use the `StandardScaler()` module from scikit-learn to normalize the data from the CSV file
market_data_scaled = StandardScaler().fit_transform(df_market_data[['price_change_percentage_24h', 'price_change_percentage_7d',
                                                                    'price_change_percentage_14d', 'price_change_percentage_30d',
                                                                    'price_change_percentage_60d', 'price_change_percentage_200d',
                                                                    'price_change_percentage_1y']])

In [6]:
# Create a DataFrame with the scaled data
market_data_scaled_df = pd.DataFrame(market_data_scaled, columns=['price_change_percentage_24h', 'price_change_percentage_7d',
                                                                    'price_change_percentage_14d', 'price_change_percentage_30d',
                                                                    'price_change_percentage_60d', 'price_change_percentage_200d',
                                                                    'price_change_percentage_1y'])

# Copy the crypto names from the original data
market_data_scaled_df['coin_id'] = df_market_data.index

# Set the coinid column as index
market_data_scaled_df = market_data_scaled_df.set_index('coin_id')

# Display sample data
market_data_scaled_df.head()

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                 
bitcoin                          0.508529                    0.493193   
ethereum                         0.185446                    0.934445   
tether                           0.021774                   -0.706337   
ripple                          -0.040764                   -0.810928   
bitcoin-cash                     1.193036                    2.000959   

              price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                  
bitcoin                          0.772200                     0.235460   
ethereum                         0.558692                    -0.054341   
tether                          -0.021680                    -0.061030   
ripple                           0.249458                    -0.050388   
bitcoin-cash                     1.760610                     0.545842   

              price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                   
bitcoin                         -0.067495                     -0.355953   
ethereum                        -0.273483                     -0.115759   
tether                           0.008005                     -0.550247   
ripple                          -0.373164                     -0.458259   
bitcoin-cash                    -0.291203                     -0.499848   

              price_change_percentage_1y  
coin_id                                   
bitcoin                        -0.251637  
ethereum                       -0.199352  
tether                         -0.282061  
ripple                         -0.295546  
bitcoin-cash                   -0.270317

---

### Find the Best Value for k Using the Original Data.

In [7]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1, 11))

In [8]:
# Create an empty list to store the inertia values
inertia = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_scaled`
# 3. Append the model.inertia_ to the inertia list

for value in k:
    k_model = KMeans(n_clusters=value, n_init='auto', random_state=1)
    k_model.fit(market_data_scaled_df)
    inertia.append(k_model.inertia_)


In [9]:
# Create a dictionary with the data to plot the Elbow curve
orig_elbow_dict = {
    'K': k,
    'inertia': inertia
}

# Create a DataFrame with the data to plot the Elbow curve

orig_elbow_df = pd.DataFrame(orig_elbow_dict)
orig_elbow_df

K     inertia
0   1  287.000000
1   2  212.123342
2   3  165.136752
3   4   79.022435
4   5   66.413051
5   6   61.634088
6   7   46.074467
7   8   43.392694
8   9   32.913223
9  10   30.469111

In [10]:
# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.
hvplot.extension('bokeh')
orig_elbow_plot = orig_elbow_df.hvplot.line(
    x="K",
    y="inertia",
    xticks=k,
    title = "Original Data"
)
orig_elbow_plot

:Curve   [K]   (inertia)

#### Answer the following question: 

**Question:** What is the best value for `k`?

**Answer:** The optimal value for k is 4. This is the point at which the "elbow" in the curve appears, where the data points become tightly clustered.

---

### Cluster Cryptocurrencies with K-means Using the Original Data

In [11]:
# Initialize the K-Means model using the best value for k
orig_model = KMeans(n_clusters=4, n_init='auto', random_state=1)

In [12]:
# Fit the K-Means model using the scaled data
orig_model.fit(market_data_scaled_df)

KMeans(n_clusters=4, random_state=1)

In [13]:
# Predict the clusters to group the cryptocurrencies using the scaled data
scaled_clusters_predicted = orig_model.predict(market_data_scaled_df)

# Print the resulting array of cluster values.
scaled_clusters_predicted

array([2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 2, 0, 0, 1, 0, 0, 0, 0])

In [14]:
# Create a copy of the DataFrame
scaled_clusters_predicted_df = market_data_scaled_df.copy()

In [15]:
# Add a new column to the DataFrame with the predicted clusters
scaled_clusters_predicted_df["group"] = scaled_clusters_predicted

# Display sample data
scaled_clusters_predicted_df.head()

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                 
bitcoin                          0.508529                    0.493193   
ethereum                         0.185446                    0.934445   
tether                           0.021774                   -0.706337   
ripple                          -0.040764                   -0.810928   
bitcoin-cash                     1.193036                    2.000959   

              price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                  
bitcoin                          0.772200                     0.235460   
ethereum                         0.558692                    -0.054341   
tether                          -0.021680                    -0.061030   
ripple                           0.249458                    -0.050388   
bitcoin-cash                     1.760610                     0.545842   

              price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                   
bitcoin                         -0.067495                     -0.355953   
ethereum                        -0.273483                     -0.115759   
tether                           0.008005                     -0.550247   
ripple                          -0.373164                     -0.458259   
bitcoin-cash                    -0.291203                     -0.499848   

              price_change_percentage_1y  group  
coin_id                                          
bitcoin                        -0.251637      2  
ethereum                       -0.199352      2  
tether                         -0.282061      0  
ripple                         -0.295546      0  
bitcoin-cash                   -0.270317      2

In [16]:
# Create a scatter plot using hvPlot by setting 
# `x="price_change_percentage_24h"` and `y="price_change_percentage_7d"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.

hvplot.extension('bokeh')
scaled_clusters_plot = scaled_clusters_predicted_df.hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by="group",
    hover_cols=['coin_id'],
    title = "Crypto Clusters - Scaled Data"
)
scaled_clusters_plot

# To assure that the crypto name was correctly added to the hover_cols parameter, the following source was consulted: 
# https://stackoverflow.com/questions/59678780/show-extra-columns-when-hovering-in-a-scatter-plot-with-hvplot

:NdOverlay   [group]
   :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)

---

### Optimize Clusters with Principal Component Analysis.

In [17]:
# Create a PCA model instance and set `n_components=3`.
pca = PCA(n_components=3)

In [18]:
# Use the PCA model with `fit_transform` to reduce to 
# three principal components.
pca_clusters_predicted = pca.fit_transform(scaled_clusters_predicted_df)

# View the first five rows of the DataFrame. 
pca_clusters_predicted[:5]

array([[ 0.44890795, -1.24537573, -0.8506404 ],
       [ 0.49536709, -0.899823  , -1.31755943],
       [-0.81884571,  0.07189909,  0.69501507],
       [-0.84035711,  0.08005407,  0.54435952],
       [ 0.81324004, -2.66952035, -1.64332113]])

In [19]:
# Retrieve the explained variance to determine how much information 
# can be attributed to each principal component.
pca.explained_variance_ratio_

array([0.34871677, 0.31363391, 0.22627118])

#### Answer the following question: 

**Question:** What is the total explained variance of the three principal components?

**Answer:** The total explained variance is .88862186, or approximately 88.9%. And of that total variance, approximately 34.9% is explained by the 
first principal component, 31.4% by the second component, and 22.6% by the third.

In [20]:
# Create a new DataFrame with the PCA data.

# Creating a DataFrame with the PCA data
pca_clusters_predicted_df = pd.DataFrame(pca_clusters_predicted, columns=['PC1', 'PC2', 'PC3'])

# Copy the crypto names from the original data
pca_clusters_predicted_df ['coin_id'] = df_market_data.index

# Set the coinid column as index
pca_clusters_predicted_df = pca_clusters_predicted_df.set_index('coin_id')

# Display sample data
pca_clusters_predicted_df.head()

PC1       PC2       PC3
coin_id                                   
bitcoin       0.448908 -1.245376 -0.850640
ethereum      0.495367 -0.899823 -1.317559
tether       -0.818846  0.071899  0.695015
ripple       -0.840357  0.080054  0.544360
bitcoin-cash  0.813240 -2.669520 -1.643321

---

### Find the Best Value for k Using the PCA Data

In [21]:
# Create a list with the number of k-values from 1 to 11
k = (range(1, 11))

In [22]:
# Create an empty list to store the inertia values
inertia = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_pca`
# 3. Append the model.inertia_ to the inertia list

for value in k:
  pca_model = KMeans(n_clusters = value, n_init='auto', random_state=1)
  pca_model.fit(pca_clusters_predicted_df)
  inertia.append(pca_model.inertia_)

In [23]:
# Create a dictionary with the data to plot the Elbow curve
pca_elbow_dict = {
    'K': k,
    'inertia': inertia
}

# Create a DataFrame with the data to plot the Elbow curve
pca_elbow_df = pd.DataFrame(pca_elbow_dict)
pca_elbow_df.head()

K     inertia
0  1  290.622694
1  2  207.307439
2  3  123.126951
3  4   44.130602
4  5   33.217427

In [24]:
# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.
hvplot.extension('bokeh')
pca_elbow_plot = pca_elbow_df.hvplot.line(
    x='K',
    y='inertia',
    xticks=k,
    title = "PCA Data"
)
pca_elbow_plot

:Curve   [K]   (inertia)

#### Answer the following questions: 

* **Question:** What is the best value for `k` when using the PCA data?

  * **Answer:** The best value for k, using the PCA data, is again, 4.


* **Question:** Does it differ from the best k value found using the original data?

  * **Answer:** The k-value using PCA data does not differ from the k-value using the original data. Both show 4 as being the optimal value.

### Cluster Cryptocurrencies with K-means Using the PCA Data

In [25]:
# Initialize the K-Means model using the best value for k
best_k_model = KMeans(n_clusters=4, n_init='auto', random_state=1)

In [26]:
# Fit the K-Means model using the PCA data
best_k_model.fit(pca_clusters_predicted_df)

KMeans(n_clusters=4, random_state=1)

In [27]:
# Predict the clusters to group the cryptocurrencies using the PCA data
clusters_group_crypto = best_k_model.predict(pca_clusters_predicted_df)

# Print the resulting array of cluster values.
clusters_group_crypto

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 1, 0, 0, 2, 0, 0, 0, 0])

In [33]:
# Create a copy of the DataFrame with the PCA data
clusters_group_crypto_df = pca_clusters_predicted_df.copy()

# Add a new column to the DataFrame with the predicted clusters
clusters_group_crypto_df["group"] = clusters_group_crypto

# Display sample data
clusters_group_crypto_df.head()

PC1       PC2       PC3  group
coin_id                                          
bitcoin       0.448908 -1.245376 -0.850640      1
ethereum      0.495367 -0.899823 -1.317559      1
tether       -0.818846  0.071899  0.695015      0
ripple       -0.840357  0.080054  0.544360      0
bitcoin-cash  0.813240 -2.669520 -1.643321      1

In [35]:
# Create a scatter plot using hvPlot by setting 
# `x="PC1"` and `y="PC2"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.

hvplot.extension('bokeh')
crypto_clusters_plot = clusters_group_crypto_df.hvplot.scatter(
    x='PC1',
    y='PC2',
    by='group',
    hover_cols=['coin_id'],
    title = "Crypto Clusters - PCA Data"
)
crypto_clusters_plot

:NdOverlay   [group]
   :Scatter   [PC1]   (PC2,coin_id)

### Visualize and Compare the Results

In this section, you will visually analyze the cluster analysis results by contrasting the outcome with and without using the optimization techniques.

In [31]:
# Composite plot to contrast the Elbow curves
hvplot.extension('bokeh')
orig_elbow_plot + pca_elbow_plot

:Layout
   .Curve.I  :Curve   [K]   (inertia)
   .Curve.II :Curve   [K]   (inertia)

In [36]:
# Composite plot to contrast the clusters
hvplot.extension('bokeh')
scaled_clusters_plot + crypto_clusters_plot

:Layout
   .NdOverlay.I  :NdOverlay   [group]
      :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)
   .NdOverlay.II :NdOverlay   [group]
      :Scatter   [PC1]   (PC2,coin_id)

#### Answer the following question: 

  * **Question:** After visually analyzing the cluster analysis results, what is the impact of using fewer features to cluster the data using K-Means?

  * **Answer:** By using fewer features to cluster the data through K-Means, the number of data points that appear is reduced. In contrast to the
  * scatter plot of results with scaled data, the scatter plot of results with PCA data shows fewer data points, ones that are more narrowly clustered.
  * And along with that, there are also fewer groups of data points that are visible.